### ISSUE TITLE
"invalid syntax" error

### ISSUE THREAD

**Issue by merspieler** [nhooyr/outPorts#3]
```
$ go run main.go 1-1024s -w1 -t10
success on port 53
success on port 21
success on port 22
outPorts: strconv.ParseUint: parsing "": invalid syntax
exit status 1
```

```
$ go version
go version go1.7.4
```

**Comment by merspieler** [comment]
Any update on this?

**Comment by nhooyr** [comment]
This is a deprecated program. I don't support it anymore.

If you are interested in figuring out why its erroring, look for the usages of strconv.ParseUint in the main.go file and see what variable is being passed in. Its empty for some reason.

**Comment by merspieler** [comment]
ok... too bad ;-/
A statement in the project description and the README about this would be good ;-)
